# Generated by Django 4.1.5 on 2023-06-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('pub_date', models.DateField()),
                ('category', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='', upload_to='things/images')),
            ],
        ),
    ]
