# Generated by Django 4.1.5 on 2023-07-02 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0005_alter_studentprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image1',
            field=models.ImageField(default='', upload_to='myapp/images'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='Batch',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='Faculty',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='image2',
            field=models.ImageField(default='', upload_to='myapp/images'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
